### ISSUE TITLE
Markup differences

### ISSUE THREAD

**Issue by zedeus** [zyachel/quetre#1]
Wonderful project! I noticed the formatting/markup is lacking a little bit.

#### Example 1: https://quetre.herokuapp.com/How-does-Melatonin-work-on-the-brain/

The way Quetre displays it is much more condensed, which imo lowers readability a lot. It's harder to distinguish sections and paragraphs. Not sure if this was done on purpose, but I'd suggest leaning a little closer to the way Quora renders it.

Quora
![image](https://user-images.githubusercontent.com/9434921/168471880-141ab1c0-7347-4b39-b074-60e20f36a626.png)

Quetre
![image](https://user-images.githubusercontent.com/9434921/168471887-263a2f68-16d3-4e07-bd80-951b691d2d8e.png)

#### Example 2: https://quetre.herokuapp.com/What-Skyrim-race-is-the-most-Croatian/

Missing formatting.

Quora
![image](https://user-images.githubusercontent.com/9434921/168472038-e131c804-843e-46de-8793-e1ec252da373.png)

Quetre
![image](https://user-images.githubusercontent.com/9434921/168472481-d138e6f0-7a82-4801-935c-40cfee1e27c3.png)

**Comment by zyachel** [comment]
Yes, the bottom padding on Quora for paragraphs is 1em. Here I was intentionally being conservative. Nonetheless, I'll change it to 1em.  

As for the missing formatting, I'll look into that this weekend. 

PS: thanks! The project is heavily inspired by your nitter and orenom's teddit.

**Comment by zyachel** [comment]
is is alright now, @zedeus?  

the padding:
![issue__padding](https://user-images.githubusercontent.com/97783235/169504305-7233fc61-61ea-4e23-bf77-476ae7465a1a.png)  
  
and the formatting
![issue__formatting](https://user-images.githubusercontent.com/97783235/169504269-9884d4fd-4194-4594-98a6-dcb9bdb4a6dd.png)

**Comment by zedeus** [comment]
That's great! A minor change that would be nice is for the ordered lists to have 0.7em vertical spacing instead of 1em, right now it's a bit too much (example below). Also, bold text doesn't work for me on Chrome unless the font-weight is increased from 550 to 600.

![image](https://user-images.githubusercontent.com/9434921/169536925-a33e36fc-d552-4133-9032-5bd32400968c.png)

**Comment by zyachel** [comment]
good catch! I almost forgot that chromium-based browsers are what most people use :p  

changed the weight to 600 and reduced the padding for unordered list items.  
![issue__unordered-list](https://user-images.githubusercontent.com/97783235/169550596-a895f936-eeb6-4202-b0d1-5f29fc89bd4a.png)

**Comment by zedeus** [comment]
Nice! One last thing, the line-height is a bit high at 1.5, whereas Quora uses 1.4. I don't have a specific preference and this doesn't matter that much, just noticed there was extra spacing when comparing the two.

**Comment by zyachel** [comment]
yeah, earlier i had set the line-height in paragraphs to 1.3, but disabled it as it looked cramped. 1.4 looks reasonable enough. I've made the change.

**Comment by zedeus** [comment]
Sweet, looks great now!
