### ISSUE TITLE
All instances give Error 400 when trying to look at an answer...

### ISSUE THREAD

**Issue by gi-yt** [zyachel/quetre#10]
I have tried restarting the service for quora.vern.cc but that didnt fix anything

**Comment by zyachel** [comment]
must be Quora changing their HTML again. Let me look into it.

**Comment by zyachel** [comment]
Quora rearranged their inline scripts. It should be working now.

Thanks for letting me know!

**Comment by zyachel** [comment]
@thefrenchghosty and @toyboatcash, you might also want to update your instances.

**Comment by gi-yt** [comment]
i have updated quora.vern.cc
