### ISSUE TITLE
[INSTANCES] (REMOVE) quetre.marcopisco.com

### ISSUE THREAD

**Issue by NoPlagiarism** [zyachel/quetre#106]
quote from [marcopisco.com](https://marcopisco.com/):

> For the services, we've lost our main website back in January. We never bothered to fix

**Comment by zyachel** [comment]
thanks for informing!

**Comment by marcoapisco** [comment]
Hi there. After doing some googling thank you for informing them.

It is correct that we lost our infrastructure and are not planning on hosting services anymore.
