### ISSUE TITLE
Remove instance of "Esmail EL BoB"

### ISSUE THREAD

**Issue by MagicLike** [zyachel/quetre#107]
Esmail is actively forbidding members or supporters of the LGBTQIA+ community to use their services via a TOS document*.
This is absolutely queerphobic and extremely discriminating. Therefore I ask to remove their instance `quetre.esmailelbob.xyz` / `quetre.esmail5pdn24shtvieloeedh7ehz3nrwcdivnfhfcedl7gf4kwddhkqd.onion` from the list, to not further support their actions.

*See the commit here: ~~https://github.com/EsmailELBoBDev2/upptime/commit/c46b9bfd03b211dff2b87737da2de33629685a5a~~ -> https://web.archive.org/web/20230522041632/https://github.com/EsmailELBoBDev2/upptime/commit/c46b9bfd03b211dff2b87737da2de33629685a5a

**Comment by zyachel** [comment]
Hey there!
The link you shared is dead and I can't visit maintainer's website either.

**Comment by MagicLike** [comment]
> Hey there! The link you shared is dead and I can't visit maintainer's website either.

You can view it here: https://web.archive.org/web/20230522041632/https://github.com/EsmailELBoBDev2/upptime/commit/c46b9bfd03b211dff2b87737da2de33629685a5a

**Comment by zyachel** [comment]
Oh, I didn't think of archive.org. thanks for that!

@EsmailELBoBDev2, don't you think preventing certain groups from accessing a service is against the free software philosophy?

@MagicLike, please understand that listing an instance doesn't imply support. The list is there for users' convenience only.

**Comment by IF-Adin** [comment]
> @MagicLike, please understand that listing an instance doesn't imply support. The list is there for users' convenience only.

This isn't about support or not. The TOS is breaking the code of conduct of Github (and practically any other service in existence) by specifically discriminating against groups of people.

No one is saying you support this, but leaving the instance on the list after knowing this does seem a bit strange.

**Comment by zyachel** [comment]
That was in response to  magiclike saying
> ... to not further support their actions.  

As for leaving the instance on the list, I am waiting for esmail's response.

**Comment by MagicLike** [comment]
> As for leaving the instance on the list, I am waiting for esmail's response.

Esmail has not responded to this by now. Any updates?

**Comment by zyachel** [comment]
I'll remove the instance as it's not reachable anyway.

**Comment by zyachel** [comment]
@EsmailELBoBDev2, in case you wish to relist the instance, feel free to open a new issue answering https://github.com/zyachel/quetre/issues/107#issuecomment-1565959715.
