### ISSUE TITLE
IP Banned as an instance

### ISSUE THREAD

**Issue by SudoVanilla** [zyachel/quetre#120]
Hi there, I started hosting an instance for Quetre just 3 weeks ago, it has come to my attention now that Quora may of banned my IP address and it probably has to do with my instance. This instance is on your list by the way.

My instance is https://ask.sudovanilla.com.

With VPN enabled:
![image](https://github.com/zyachel/quetre/assets/51213244/821c6f64-4ab5-4acb-bc6c-29a60802270f)

Without VPN enabled:
![image](https://github.com/zyachel/quetre/assets/51213244/162bbf03-cabb-4a66-bb87-2c55c41075a6)

**Comment by SudoVanilla** [comment]
I also use Cloudflare and I can see this kind of data, let's just say someone heavily used it this morning at 9:30am EST.


![image](https://github.com/zyachel/quetre/assets/51213244/4126dc3f-e1d3-4dbc-b831-fe3402ccb3fb)

**Comment by zyachel** [comment]
have you enabled redis for caching? it really helps with the rate-limiting.  
it had happened with my instance twice before I added redis support.  
I'd strongly suggest you to do that.  

quora is aggressive with rate-limiting, so there's not much I can do. though this is temporary.  

if you're still being hammered by requests, maybe you can do your own rate-limiting via cloudflare? I'm sure they have a setting for that.

**Comment by SudoVanilla** [comment]
This issue has been looked into further thanks.
The IP ban should expire within 24 hours according to Quora support and I have set a rate limit via Cloudflare.
