### ISSUE TITLE
non www subdomains of quora

### ISSUE THREAD

**Issue by idnovic** [zyachel/quetre#131]
Hello,

are non www subdomains supported?

e.g.

https://de.quora.com/Je-mehr-Du-Dich-entfernst-umso-mehr-siehst-Du-Je-mehr-Du-dann-aus-der-Entfernung-siehst-erkennst-Du-wie-unwichtig-alles-ist-Stimmst-Du-dem-zu

de for the german language instead of www

**Comment by zyachel** [comment]
yes, language is passed as a query param.  

so, your example link would become:  
https://quetre.iket.me/Je-mehr-Du-Dich-entfernst-umso-mehr-siehst-Du-Je-mehr-Du-dann-aus-der-Entfernung-siehst-erkennst-Du-wie-unwichtig-alles-ist-Stimmst-Du-dem-zu?lang=de  

to avoid rewriting the URLs manually, you can use [helpers](https://github.com/zyachel/quetre?tab=readme-ov-file#automatic-redirection)
