### ISSUE TITLE
Add qr.zorby.top

### ISSUE THREAD

**Issue by Troughy** [zyachel/quetre#133]
URL: https://qr.zorby.top
Country: Germany
Provider: Pawhost.de
Cloudflare: false
(edit: switched providers)

**Comment by Troughy** [comment]
Sorry, I just checked and see there's a bad gateway error, it's probably because of the custom port, I'll try to fix it asap

**Comment by Troughy** [comment]
Okay, fixed it!

**Comment by Troughy** [comment]
This instance is now also available over tor: iuryhavpcvc5unkojuobya6efmromgyatc3dspw5arulgqxch4bylcqd.onion
Also i2p: fytmh2fqkg2q4dwtu4eqe6qi24hvivjtkhciv7e3gch35wkh4dpq.b32.i2p

**Comment by zyachel** [comment]
thanks for hosting! give me some time to add it to the readme since I don't have access to my computer ATM.
