### ISSUE TITLE
remove dead instances

### ISSUE THREAD

**Issue by zyachel** [zyachel/quetre#138]
hey @hnhx, @unstablemaple, @toyboatcash, @Troughy,  @ProjectSegfault, and @NoPlagiarism

your instances are either broken or unavailable. please let me know if and when you fix them so that i can re-add them to the list.  

see: https://codeberg.org/zyachel/quetre/pulls/39 for details

**Comment by zyachel** [comment]
done in 5dd94140a4b136dc13723fcfc71a3f14bc289126

**Comment by NoPlagiarism** [comment]
I'm not affiliated with whateveritworks.org, but yes. They seems pretty dead

Sorry for inconvenience
