### ISSUE TITLE
Doesn't work for french version

### ISSUE THREAD

**Issue by stemy2** [zyachel/quetre#14]
Hello,

I'd like to use it with the french version of quora, but it doesn't work since it uses the "fr" subdomain and give me a http 404 error.

**Comment by zyachel** [comment]
hey there!  

All routes involving subdomains(primarily language-specific routes and spaces) are not implemented yet.  

I have a vague idea on how I'll implement them.  
I'm thinking of something like this:   
``https://fr.quora.com/A-quoi-ressemblerait-la-4D`` redirects to ``https://quetre.herokuapp.com/fr/A-quoi-ressemblerait-la-4D``.  

But that'll require extra support from redirector extensions.  

Or alternatively, I could manually parse any link a user pastes. for example: if a user appends the link after ``quetre.herokuapp.com/?link=``(like this: ``https://quetre.herokuapp.com/?link=https://fr.quora.com/A-quoi-ressemblerait-la-4D``), then I could do some checks and fetch the resource.  

In any case, I'll only be able to implement the functionality when I get some time(possibly, by next month).

**Comment by kareem-dj** [comment]
> https://fr.quora.com/A-quoi-ressemblerait-la-4D redirects to https://quetre.herokuapp.com/fr/A-quoi-ressemblerait-la-4D.
I added this to my PR :)

**Comment by zyachel** [comment]
the feature is now implemented. you need to pass a query param(e.g.: `?lang=ar`) to see answer in another language.
Or alternatively, you can choose language while searching.
