### ISSUE TITLE
couldn't retrieve data error

### ISSUE THREAD

**Issue by gi-yt** [zyachel/quetre#2]
i installed & started quetre with pnpm as told in README.
but i get this error when i try to go to some link
```
🔴 couldn't retrieve data
Error: couldn't retrieve data
    at fetcher (file:///home/ak/projects/quetre/fetchers/fetcher.js:37:25)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async getAnswers (file:///home/ak/projects/quetre/fetchers/getAnswers.js:12:15)
    at async file:///home/ak/projects/quetre/controllers/viewController.js:25:23 

```

**Comment by zyachel** [comment]
oh, so sorry. Quora changed their HTML a couple of days ago that broke the fetcher.js script.  
I fixed it and even pushed it to heroku but forgot to push it here. :p 
I have done so just now after reading your comment.  
It should work now should you try again.

**Comment by gi-yt** [comment]
works now. thanks!
