### ISSUE TITLE
Search functionality

### ISSUE THREAD

**Issue by uranuspucksaxophone** [zyachel/quetre#21]
I think that the only thing quetre needs to be perfect is to be able to search.

Oh, and thank you for creating this @zyachel , I was sick of quora without account.

**Comment by zyachel** [comment]
Yes, I'm on it!
Will add the search functionality just after I refactor some code and add profile route.

The code to profile page is going to be very similar to the code for answers. Therefore, I need to first refactor the code. It'll take a couple of days.

You can expect search functionality before 3rd week of August, if everything goes as planned.

And I'm glad you find this helpful :)
