### ISSUE TITLE
How does it work?

### ISSUE THREAD

**Issue by EsmailELBoBDev2** [zyachel/quetre#37]
Excuse me but how I use it?? normally in nitter or any other software you can replace URLs but for some reason when I do it here I get 404 page so how am I supposed to use it?

**Comment by zyachel** [comment]
it works the same way. you replace the domain name(www.quora.com) with any instance's domain name.  

it might show a 404 page on some routes that aren't yet implemented(eg: `/profile/some-name`).  

but for any answer route, it should work normally.  

can i get a sample URL which you were trying to access?

**Comment by EsmailELBoBDev2** [comment]
Yeah..it's awkward now it works, tried it multiple times and works fine now so like my other comment https://github.com/zyachel/libremdb/issues/12#issuecomment-1193503232 all things are good

unsure why it used to display 404 maybe browser cache issue
