### ISSUE TITLE
Error 500: something went wrong!

### ISSUE THREAD

**Issue by NebulaOnion** [zyachel/quetre#49]
In my experience, this may mean that Quora is rate-limiting this instances, since the little-known ones don't seem affected by this. Oh and @zyachel, I think that the Codeberg-GitHub bridge is broken, some issues and PRs that are on Codeberg aren't shown here.

**Comment by zyachel** [comment]
Yeah, Quora sometimes send `403`(forbidden) instead of the usual `429`(rate-limited) as the response.  
I'll add that little check in fetcher.js

As for the codeberg, it's not a mirror repository, I push the code to both individually.

**Comment by zyachel** [comment]
fixed in 86df58367a147939ebd4057071d5450556737eac
