### ISSUE TITLE
Favicons PNG have a background

### ISSUE THREAD

**Issue by TheFrenchGhosty** [zyachel/quetre#5]
This [commit](https://github.com/zyachel/quetre/commit/ab335afb6a202396b57882cb9dc8c159d584e654) changed the favicons from PNG with a dark background, to PNG with a white background.

This looks the PNG having a background like it wasn't done on purpose.

**Comment by zyachel** [comment]
yes, I wanted to keep the background transparent.
let me fix it real quick.

**Comment by zyachel** [comment]
Check now @TheFrenchGhosty. I made new transparent favicons.
