### ISSUE TITLE
Instance does not render JavaScript

### ISSUE THREAD

**Issue by StandingPadAnimations** [zyachel/quetre#66]
So I followed the instructions (I cloned from both GitHub and Codeberg) on my Raspberry Pi and this is the result I get: 
![image](https://user-images.githubusercontent.com/75058058/187043955-c5762bcb-65e7-449b-a2ed-d3c9f04b6ec7.png)

It seems like JavaScript isn't being rendered, but I have no idea why

**Comment by StandingPadAnimations** [comment]
Investigating a little more, it seems like it works on the Raspberry Pi itself, but not when I try to use it directly from my PC
![image](https://user-images.githubusercontent.com/75058058/187046814-a78d92c6-1ee5-4760-ab24-22ad0c7ffe02.png)

**Comment by zyachel** [comment]
Can you try again with latest commit(dfec2b5ebd0413606f64cd9f67a370aaf3d809fa) and see if it fixes that?  

Remember to set ``NO_UPGRADE=1`` in .env

**Comment by thecashewtrader** [comment]
Should we close this since #60 has been merged?

**Comment by zyachel** [comment]
I was waiting for @StandingPadAnimations to respond.

**Comment by StandingPadAnimations** [comment]
I haven't tested it yet. I'll test it when I get the chance

**Comment by StandingPadAnimations** [comment]
Ok after a thousand years, no change
![image](https://user-images.githubusercontent.com/75058058/221326499-53a40352-5249-40c7-83cd-dc9eac02391e.png)

**Comment by StandingPadAnimations** [comment]
Never mind, I needed to set `NO_UPGRADE` to 1
