### ISSUE TITLE
All available instances of Quetre return either 404 or 503 for any Quora page

### ISSUE THREAD

**Issue by shindouj** [zyachel/quetre#68]
Since yesterday, I am trying to host a Quetre instance, but I have noticed it always returns 404 Recheck the URL for any Quora page I tried, including the one in the FAQ (https://quetre.iket.me/Are-Nubians-nilotes). 

I have retried this request on all or almost all listed instances and each and every one either returns 404 Recheck the URL, or 503 Rate Limit error. Is this possibly a change on Quora's side?

**Comment by zyachel** [comment]
Yeah, it was Quora doing its thing.  
Thanks for reporting.

**Comment by shindouj** [comment]
Interesting - both the URL in my ticket and my own instance (https://quetre.jeikobu.net/Are-Nubians-nilotes) are working for me just fine. Perhaps you should consider creating a separate issue ticket?
