### ISSUE TITLE
 quora.vern.cc redirects to Invidious

### ISSUE THREAD

**Issue by vairag22** [zyachel/quetre#8]
[quora.vern.cc](https://quora.vern.cc/feed/popular) redirects to vern's Invidious instance. I tried to contact the maintainer  but the link provided in the [README](https://github.com/zyachel/quetre#instances=) also redirects to his Invidious instance. 

Please try to contact him and fix this issue but until then [quora.vern.cc](https://quora.vern.cc/feed/popular) should be removed.

**Comment by zyachel** [comment]
i can visit the website just fine. 

![quora](https://user-images.githubusercontent.com/97783235/174483934-64418ca7-48dd-42c7-ae6d-aa1708fc83c1.png)

could you recheck?

**Comment by vairag22** [comment]
Now it's fixed. Maybe it was a DNS issue.

**Comment by gi-yt** [comment]
hi, the issue was that our server was down, so it was running backup serverwhich only  has invidious and our main website...
